# Generated by Django 4.2.9 on 2024-02-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('house_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.houses')),
            ],
        ),
    ]
