# Generated by Django 5.0.1 on 2024-02-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_owner_options_alter_owner_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='House_rent',
            field=models.CharField(choices=[('15000', '15000'), ('25000', '25000'), ('35000', '35000'), ('50000', '50000')], default='15000', max_length=20),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_type',
            field=models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('1 Bedroom', 'One Bedroom'), ('2 Bedroom', 'Two Bedroom'), ('3 Bedroom', 'Three Bedroom')], default='Bedsitter', max_length=20),
        ),
    ]
