# Generated by Django 4.2.9 on 2024-02-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_houses_house_rent_alter_houses_house_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='complaint',
            field=models.TextField(null=True),
        ),
    ]
