# Generated by Django 4.2.10 on 2024-02-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_whatsappmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='receiver',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
