# Generated by Django 4.2.10 on 2024-02-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_alter_whatsappmessage_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='house',
        ),
        migrations.AddField(
            model_name='houses',
            name='cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.customers'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='vacancy',
            field=models.CharField(choices=[('Occuppied', 'Occuppied'), ('Booked', 'Booked'), ('Vacant', 'Vacant'), ('Maintenance', 'Maintenance')], default='Vacant', max_length=20),
        ),
    ]
