# Generated by Django 4.2.10 on 2024-02-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_customers_house_houses_cust_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='cust_id',
            new_name='customer_id',
        ),
    ]
