# Generated by Django 4.2.10 on 2024-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_rename_cust_id_houses_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
