# Generated by Django 4.2.10 on 2024-02-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_customers_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses',
            name='customer_id',
        ),
    ]
