# Generated by Django 4.2.10 on 2024-02-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_houses_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='chatbot.customers'),
        ),
    ]
