# Generated by Django 4.2.10 on 2024-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_remove_houses_cust_id_houses_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
