# Generated by Django 4.2.9 on 2024-03-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_remove_houses_customer_remove_invoice_paybill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.houses'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='assigned_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.houses'),
        ),
    ]
