# Generated by Django 4.2.9 on 2024-03-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_remove_invoice_customer_id_remove_invoice_house_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='month',
        ),
    ]
