# Generated by Django 3.2.16 on 2024-03-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_invoice_arrears_invoice_fines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='awaiting_response',
            field=models.BooleanField(default=False),
        ),
    ]
