# Generated by Django 3.2.16 on 2024-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0025_customers_awaiting_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('selected_house_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
