# Generated by Django 3.2.16 on 2024-03-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0031_alter_whatsappmessage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='body',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
